# Generated by Django 4.2 on 2025-01-27 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_stock_low_stock_threshold_stock_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='garage.customer'),
            preserve_default=False,
        ),
    ]
