# Generated by Django 4.2 on 2025-01-27 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_servicerecord_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='garage.customer'),
        ),
    ]
