# Generated by Django 4.2 on 2025-01-27 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_alter_servicerecord_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerecord',
            name='customer',
        ),
    ]
